### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jamiebyer** [jamiebyer/image_effects#1]
- [x] reorganize folder (windows)
- [ ] set up so the gui doesn't interfere on the windows side
- [x] make input and output image folders
- [ ] change path so its usable on other computers
- [ ] Preview selected image
- [ ] non-solid background
- [ ] canvas background
- [ ] blur background? make background a selected colour // transparent?
- [ ] stretch image to be square/rectangular
- [ ] switch to other image crate (?)
